create table customer (
    customer_id bigint generated by default as identity primary key,
    store_id bigint not null references store(store_id),
    first_name citext not null,
    last_name citext not null,
    email citext,
    address_id bigint not null references address(address_id),
    active boolean not null default true,
    create_date timestamp not null,
    last_update timestamp default current_timestamp
);

create index idx_customer_store on customer(store_id);
create index idx_customer_address on customer(address_id);
create index idx_last_name on customer(last_name);
