create table store (
    store_id bigint generated by default as identity primary key,
    manager_staff_id bigint not null references staff(staff_id) unique,
    address_id bigint not null references address(address_id),
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_store_address on store(address_id);
