create table actor (
    actor_id bigint generated by default as identity primary key,
    first_name citext not null,
    last_name citext not null,
    last_update timestamp not null default current_timestamp
);

create index idx_actor_last_name on actor(last_name);
create index idx_actor_first_name on actor(first_name);