create table address (
    address_id bigint generated by default as identity primary key,
    address citext not null,
    address2 citext,
    district citext not null,
    city_id bigint not null references city(city_id),
    postal_code citext,
    phone citext not null,
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_address_city on address(city_id);
