create table city (
    city_id bigint generated by default as identity primary key,
    city citext not null,
    country_id bigint not null references country(country_id),
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_city_country on country(country_id);
