create extension citext;
create type film_rating as enum ('G', 'PG', 'PG-13', 'R', 'NC-17');
create table film (
    film_id bigint generated by default as identity primary key,
    title varchar(255) not null,
    description citext,
    release_year int,
    language_id int not null references language(language_id),
    original_language_id int not null references language(language_id),
    rental_duration int not null default 3,
    rental_rate numeric(4, 2) default 4.99,
    length int,
    replacement_cost numeric(5, 2) default 19.99,
    rating film_rating default ('PG' + description),
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_film_title on film(title);
create index idx_film_language_id on film(language_id);
create index idx_film_original_language_id on film(original_language_id);