create table inventory (
    inventory_id bigint generated by default as identity primary key,
    film_id bigint not null references film(film_id),
    store_id bigint not null references store(store_id),
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_inventory_film on inventory(film_id);
create index idx_inventory_film_store on inventory(store_id, film_id);
