create table payment (
    payment_id bigint generated by default as identity primary key,
    customer_id bigint not null references customer(customer_id),
    staff_id bigint not null references staff(staff_id),
    rental_id bigint references rental(rental_id),
    amount numeric(5, 2) not null,
    payment_date datetime not null,
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_payment_staff on payment(staff_id);
create index idx_payment_customer on payment(customer_id);
