create table rental (
    rental_id bigint generated by default as identity primary key,
    rental_date datetime not null,
    inventory_id bigint not null references inventory(inventory_id),
    customer_id bigint not null references customer(customer_id),
    return_date datetime,
    staff_id bigint not null references staff(staff_id),
    last_update timestamp not null default CURRENT_TIMESTAMP,

    unique (rental_date, inventory_id, customer_id)
);

create index idx_rental_inventory on rental(inventory_id);
create index idx_rental_customer on rental(customer_id);
create index idx_rental_staff on rental(staff_id);
