create table staff (
    staff_id bigint generated by default as identity primary key,
    first_name citext not null,
    last_name citext not null,
    address_id bigint references address(address_id),
    picture bytea,
    email citext,
    store_id bigint not null references store(store_id),
    active boolean not null default true,
    username citext not null,
    password citext,
    last_update timestamp not null default CURRENT_TIMESTAMP
);

create index idx_staff_store on staff(store_id);
create index idx_staff_address on address(address_id);
